# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35b705d256024b922c7afa761245ad64cf052ae80a25178e08187f8209595c11dfed5910e643701c5d5012b5063cecfa64148b684711ae43f312d6c362ed8bdf

test:
  secret_key_base: a0a0b345cf43bd3469f21b2678a56ddd373b5bb44709c6d000240b21e7d29a7a79deec6de059ad5bea81056b0d0cbed77027f1c0cfcee0388463cb45d98b7fb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
